### ISSUE TITLE
Error on install/execute - command not found

### ISSUE THREAD

**Issue by Yousha** [antonioleal/google-chrome-the-latest#1]
After installing/buildling package `google-chrome-the-latest` got this error:

> /bin/sh: line 1: google-chrome-stable: command not found

Package: google-chrome-the-latest 3.1
Command: ` /opt/google-chrome-the-latest/google-chrome-the-latest.py install`
User: root
Interpreter: Python 2.7.18
Platform: Slackware 15 64bit
Infrastructure: x64 Intel

**Comment by antonioleal** [comment]
The report is because of this line:

current_version = os.popen('google-chrome-stable --version').read().split()[2]

Script should work fine.
Version 3.2 fixes it

**Comment by antonioleal** [comment]
Fixed
